language: go

go:
- 1.11.x

os:
- linux

git:
  depth: 1

sudo: false

notifications:
  email: false

env:
- GO111MODULE=on

install:
- chmod +x scripts/install_protoc3.sh
- scripts/install_protoc.sh
- export PATH="$PWD/protoc/bin":$PATH

before_script:
- make gen-pb

script:
- go vet ./...
- make test-all