# Define the service for the raft cluster such that the
# entire cluster appears as a single unit and the distribution
# is completely transparent to the client.
apiVersion: v1
kind: Service
metadata:
  name: raft000
  namespace: raft-k8s
  labels:
    app: raft
    tier: datastore
    raft-cluster/id: raft000
    version: v0.1
spec:
  selector:
    app: raft
    tier: datastore
    raft-cluster/id: raft000
  ports:
  - nodePort: 30000
    targetPort: 7777
    protocol: TCP
    port: 30000
  type: NodePort