apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/raft0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/raft1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/raft2"
---




apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-0-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/raft0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-1-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/raft1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-2-1
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/raft2"
---




apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-0-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/raft0"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-1-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/raft1"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume-2-2
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/raft2"
---